sudo: false
dist: xenial
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
env:
- DEBUG=1
python:
  - "3.6"
install:
  - pip install -U coverage pip setuptools tox tox-travis wheel
script:
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
