[tox]
isolated_build = True
envlist =
	py{311,312}-django{50}
	py{312,314}-django{60}

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.14: py314

[testenv]
commands =
	# We need to put all of the coverage reports into the same directory, so we can tell
	# the `codecov` action to look there. The files need to be named after one of the
	# patterns in the uploader, see https://github.com/codecov/codecov-cli/blob/7432bad76c619e34d6617b578e039e7d733e3f00/codecov_cli/services/upload/file_finder.py#L11-L36
	# We use the `coverage-{envname}.xml` pattern, so we can use the `envname` variable here.
	py.test -ra -vvv --cov=paikkala --cov-report=term-missing --cov-report=xml:{toxworkdir}/coverage/coverage-{envname}.xml {posargs}
extras =
	dev
	printing
deps =
	django42: Django~=4.2.0
	django50: Django~=5.0.0
	django60: Django~=6.0.0
