# Generated by Django 2.0.5 on 2018-05-13 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='please be specific; this is not qualified by event name or similar', max_length=64)),
                ('reservation_start', models.DateTimeField(blank=True, null=True)),
                ('reservation_end', models.DateTimeField(blank=True, null=True)),
                ('invalid_after', models.DateTimeField(blank=True, help_text='the time after which tickets for this program are considered out-of-date, e.g. for hiding from UI', null=True)),
                ('max_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_number', models.IntegerField()),
                ('end_number', models.IntegerField()),
                ('capacity', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('key', models.CharField(max_length=8, unique=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='paikkala.Program')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='paikkala.Row')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='paikkala.Zone'),
        ),
        migrations.AddField(
            model_name='row',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='paikkala.Zone'),
        ),
        migrations.AddField(
            model_name='program',
            name='rows',
            field=models.ManyToManyField(to='paikkala.Row'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('program', 'zone', 'number')},
        ),
    ]
