# Generated by Django 2.0.5 on 2018-05-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_tickets_per_batch',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='program',
            name='max_tickets_per_user',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='program',
            name='require_user',
            field=models.BooleanField(default=False),
        ),
    ]
