# Generated by Django 2.0.5 on 2018-05-13 12:11

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0002_more_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='excluded_numbers',
            field=models.CharField(blank=True, help_text='seat numbers to consider not part of the row; comma-separated integers', max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
