# Generated by Django 2.0.5 on 2018-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0003_row_excluded_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='event_name',
            field=models.CharField(default='', help_text='Used to form a longer name for the program.', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
