# Generated by Django 2.0.5 on 2018-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0004_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='automatic_max_tickets',
            field=models.BooleanField(default=False, help_text='Recompute the maximum tickets field automatically based on row capacity'),
        ),
    ]
