# Generated by Django 2.1.5 on 2019-02-04 15:34

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0006_perprogramblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perprogramblock',
            name='excluded_numbers',
            field=models.CharField(blank=True, help_text='seat numbers to block from this row in this program', max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='row',
            name='excluded_numbers',
            field=models.CharField(blank=True, help_text='seat numbers to consider not part of the row; comma-separated integers', max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
