# Generated by Django 2.1.7 on 2019-02-16 09:48

from django.db import migrations, models
import paikkala.utils.ranges


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0010_nonblank_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perprogramblock',
            name='excluded_numbers',
            field=models.CharField(blank=True, help_text='seat numbers to block from this row in this program', max_length=128, validators=[paikkala.utils.ranges.validate_number_set]),
        ),
    ]
