# Generated by Django 2.1.7 on 2019-04-27 11:31

from django.db import migrations, models
import paikkala.utils.ranges


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0011_better_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='excluded_numbers',
            field=models.CharField(blank=True, help_text='seat numbers to consider not part of the row; comma-separated integers', max_length=128, validators=[paikkala.utils.ranges.validate_number_set]),
        ),
    ]
