# Generated by Django 2.0.8 on 2019-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paikkala', '0015_contact_and_hidden_seats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('room', 'ordering', 'name')},
        ),
        migrations.AddField(
            model_name='zone',
            name='ordering',
            field=models.IntegerField(default=0, help_text='Smallest first'),
        ),
    ]
